services:
  - name: jogo-scramble-cadu
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: 3000
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - src/**